### ISSUE TITLE
Deprecate _config.axi.erb in favor of a DSL

### ISSUE THREAD

**Issue by amclain** [amclain/netlinx-erb#1]
By passing a binding to ERB, [_config.axi.erb](https://github.com/amclain/netlinx-erb/blob/e22428717f34357e4fbfcd8a0fb61d18b826550a/template/include/ui/_config.axi.erb) can be replaced by a Ruby DSL or YAML config file, like:

``` yaml
touch_panels:
    ROOM_1: 10001
    ROOM_2: 10002
    ROOM_3: 10003
```

The current config file is 49 lines long and mixes configuration with implementation.
